/* tslint:disable */
/* eslint-disable */
/**
 * Shula API
 * API documentation for the Shula application
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// URLSearchParams not necessarily used
// @ts-ignore
import { URL, URLSearchParams } from 'url';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { WhatsAppQrCodeResponseDto } from '../models';
// @ts-ignore
import type { WhatsAppStatusResponseDto } from '../models';
/**
 * WhatsAppStatusApi - axios parameter creator
 * @export
 */
export const WhatsAppStatusApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get the current WhatsApp status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStatus: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/whatsapp-status`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get the current WhatsApp QR code
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWhatsAppQrCode: async (options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/api/whatsapp-status/qr-code`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * WhatsAppStatusApi - functional programming interface
 * @export
 */
export const WhatsAppStatusApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = WhatsAppStatusApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get the current WhatsApp status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getStatus(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WhatsAppStatusResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getStatus(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WhatsAppStatusApi.getStatus']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @summary Get the current WhatsApp QR code
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getWhatsAppQrCode(options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<WhatsAppQrCodeResponseDto>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getWhatsAppQrCode(options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['WhatsAppStatusApi.getWhatsAppQrCode']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * WhatsAppStatusApi - factory interface
 * @export
 */
export const WhatsAppStatusApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = WhatsAppStatusApiFp(configuration)
    return {
        /**
         * 
         * @summary Get the current WhatsApp status
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getStatus(options?: RawAxiosRequestConfig): AxiosPromise<WhatsAppStatusResponseDto> {
            return localVarFp.getStatus(options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get the current WhatsApp QR code
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getWhatsAppQrCode(options?: RawAxiosRequestConfig): AxiosPromise<WhatsAppQrCodeResponseDto> {
            return localVarFp.getWhatsAppQrCode(options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * WhatsAppStatusApi - interface
 * @export
 * @interface WhatsAppStatusApi
 */
export interface WhatsAppStatusApiInterface {
    /**
     * 
     * @summary Get the current WhatsApp status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WhatsAppStatusApiInterface
     */
    getStatus(options?: RawAxiosRequestConfig): AxiosPromise<WhatsAppStatusResponseDto>;

    /**
     * 
     * @summary Get the current WhatsApp QR code
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WhatsAppStatusApiInterface
     */
    getWhatsAppQrCode(options?: RawAxiosRequestConfig): AxiosPromise<WhatsAppQrCodeResponseDto>;

}

/**
 * WhatsAppStatusApi - object-oriented interface
 * @export
 * @class WhatsAppStatusApi
 * @extends {BaseAPI}
 */
export class WhatsAppStatusApi extends BaseAPI implements WhatsAppStatusApiInterface {
    /**
     * 
     * @summary Get the current WhatsApp status
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WhatsAppStatusApi
     */
    public getStatus(options?: RawAxiosRequestConfig) {
        return WhatsAppStatusApiFp(this.configuration).getStatus(options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get the current WhatsApp QR code
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof WhatsAppStatusApi
     */
    public getWhatsAppQrCode(options?: RawAxiosRequestConfig) {
        return WhatsAppStatusApiFp(this.configuration).getWhatsAppQrCode(options).then((request) => request(this.axios, this.basePath));
    }
}

