/* tslint:disable */
/* eslint-disable */
/**
 * Shula API
 * API documentation for the Shula application
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ConsentMessageDto
 */
export interface ConsentMessageDto {
    /**
     * The WhatsApp group ID
     * @type {string}
     * @memberof ConsentMessageDto
     */
    'whatsappGroupId': string;
    /**
     * The serialized message ID of the consent message
     * @type {string}
     * @memberof ConsentMessageDto
     */
    'consentMessageId': string;
}

