/* tslint:disable */
/* eslint-disable */
/**
 * Shula API
 * API documentation for the Shula application
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateSystemMessageDto
 */
export interface CreateSystemMessageDto {
    /**
     * Unique key for the system message
     * @type {string}
     * @memberof CreateSystemMessageDto
     */
    'key': string;
    /**
     * Content of the system message with optional placeholders
     * @type {string}
     * @memberof CreateSystemMessageDto
     */
    'content': string;
    /**
     * Category of the system message
     * @type {string}
     * @memberof CreateSystemMessageDto
     */
    'category': CreateSystemMessageDtoCategoryEnum;
    /**
     * Additional metadata for the system message
     * @type {object}
     * @memberof CreateSystemMessageDto
     */
    'metadata'?: object;
}

export const CreateSystemMessageDtoCategoryEnum = {
    Group: 'GROUP',
    Person: 'PERSON',
    Notification: 'NOTIFICATION',
    General: 'GENERAL'
} as const;

export type CreateSystemMessageDtoCategoryEnum = typeof CreateSystemMessageDtoCategoryEnum[keyof typeof CreateSystemMessageDtoCategoryEnum];


