/* tslint:disable */
/* eslint-disable */
/**
 * Shula API
 * API documentation for the Shula application
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateParticipantConsentDto
 */
export interface CreateParticipantConsentDto {
    /**
     * Group ID
     * @type {string}
     * @memberof CreateParticipantConsentDto
     */
    'groupId': string;
    /**
     * Participant ID
     * @type {string}
     * @memberof CreateParticipantConsentDto
     */
    'participantId': string;
    /**
     * Consent status
     * @type {string}
     * @memberof CreateParticipantConsentDto
     */
    'consentStatus': CreateParticipantConsentDtoConsentStatusEnum;
}

export const CreateParticipantConsentDtoConsentStatusEnum = {
    Pending: 'pending',
    Accepted: 'accepted',
    Rejected: 'rejected'
} as const;

export type CreateParticipantConsentDtoConsentStatusEnum = typeof CreateParticipantConsentDtoConsentStatusEnum[keyof typeof CreateParticipantConsentDtoConsentStatusEnum];


