/* tslint:disable */
/* eslint-disable */
/**
 * Shula API
 * API documentation for the Shula application
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateManyConsentRecords201Response
 */
export interface CreateManyConsentRecords201Response {
    /**
     * Number of records created
     * @type {number}
     * @memberof CreateManyConsentRecords201Response
     */
    'count'?: number;
}

