/* tslint:disable */
/* eslint-disable */
/**
 * Shula API
 * API documentation for the Shula application
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GroupWithCountsResponseDto
 */
export interface GroupWithCountsResponseDto {
    /**
     * Unique identifier
     * @type {string}
     * @memberof GroupWithCountsResponseDto
     */
    'id': string;
    /**
     * WhatsApp group ID
     * @type {string}
     * @memberof GroupWithCountsResponseDto
     */
    'whatsappGroupId': string;
    /**
     * Group name
     * @type {string}
     * @memberof GroupWithCountsResponseDto
     */
    'name': string;
    /**
     * Group description
     * @type {string}
     * @memberof GroupWithCountsResponseDto
     */
    'description'?: string;
    /**
     * Group status
     * @type {string}
     * @memberof GroupWithCountsResponseDto
     */
    'status': string;
    /**
     * Group creation date
     * @type {string}
     * @memberof GroupWithCountsResponseDto
     */
    'createdAt': string;
    /**
     * Number of participants in the group
     * @type {number}
     * @memberof GroupWithCountsResponseDto
     */
    'participantsCount': number;
    /**
     * Number of persons in the group
     * @type {number}
     * @memberof GroupWithCountsResponseDto
     */
    'personsCount': number;
}

