/* tslint:disable */
/* eslint-disable */
/**
 * Shula API
 * API documentation for the Shula application
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GroupEventLogItem } from './group-event-log-item';
// May contain unused imports in some cases
// @ts-ignore
import type { PaginationMetadata } from './pagination-metadata';

/**
 * 
 * @export
 * @interface GroupLogsResponseDto
 */
export interface GroupLogsResponseDto {
    /**
     * 
     * @type {Array<GroupEventLogItem>}
     * @memberof GroupLogsResponseDto
     */
    'items': Array<GroupEventLogItem>;
    /**
     * 
     * @type {PaginationMetadata}
     * @memberof GroupLogsResponseDto
     */
    'pagination': PaginationMetadata;
}

