/* tslint:disable */
/* eslint-disable */
/**
 * Shula API
 * API documentation for the Shula application
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { MediaCounts } from './media-counts';

/**
 * 
 * @export
 * @interface GroupMetricsResponseDto
 */
export interface GroupMetricsResponseDto {
    /**
     * 
     * @type {string}
     * @memberof GroupMetricsResponseDto
     */
    'groupId': string;
    /**
     * 
     * @type {object}
     * @memberof GroupMetricsResponseDto
     */
    'period': object;
    /**
     * 
     * @type {number}
     * @memberof GroupMetricsResponseDto
     */
    'messagesProcessed': number;
    /**
     * 
     * @type {MediaCounts}
     * @memberof GroupMetricsResponseDto
     */
    'mediaProcessed': MediaCounts;
}

