/* tslint:disable */
/* eslint-disable */
/**
 * Shula API
 * API documentation for the Shula application
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GroupStatsResponseDto
 */
export interface GroupStatsResponseDto {
    /**
     * Total number of active groups
     * @type {number}
     * @memberof GroupStatsResponseDto
     */
    'totalActive': number;
    /**
     * Total number of inactive groups
     * @type {number}
     * @memberof GroupStatsResponseDto
     */
    'totalInactive': number;
    /**
     * Total number of groups
     * @type {number}
     * @memberof GroupStatsResponseDto
     */
    'total': number;
}

