/* tslint:disable */
/* eslint-disable */
/**
 * Shula API
 * API documentation for the Shula application
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GroupsCreateDto
 */
export interface GroupsCreateDto {
    /**
     * WhatsApp group ID
     * @type {string}
     * @memberof GroupsCreateDto
     */
    'whatsappGroupId': string;
    /**
     * Group name
     * @type {string}
     * @memberof GroupsCreateDto
     */
    'name': string;
    /**
     * Group description
     * @type {string}
     * @memberof GroupsCreateDto
     */
    'description'?: string;
}

