/* tslint:disable */
/* eslint-disable */
/**
 * Shula API
 * API documentation for the Shula application
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GroupEventLogItem
 */
export interface GroupEventLogItem {
    /**
     * 
     * @type {string}
     * @memberof GroupEventLogItem
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof GroupEventLogItem
     */
    'groupId': string;
    /**
     * 
     * @type {string}
     * @memberof GroupEventLogItem
     */
    'eventType': GroupEventLogItemEventTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof GroupEventLogItem
     */
    'mediaType'?: GroupEventLogItemMediaTypeEnum;
    /**
     * 
     * @type {object}
     * @memberof GroupEventLogItem
     */
    'metadata'?: object;
    /**
     * 
     * @type {string}
     * @memberof GroupEventLogItem
     */
    'timestamp': string;
}

export const GroupEventLogItemEventTypeEnum = {
    MessageProcessed: 'message_processed',
    MediaProcessed: 'media_processed'
} as const;

export type GroupEventLogItemEventTypeEnum = typeof GroupEventLogItemEventTypeEnum[keyof typeof GroupEventLogItemEventTypeEnum];
export const GroupEventLogItemMediaTypeEnum = {
    Image: 'image',
    Video: 'video',
    Audio: 'audio',
    Document: 'document',
    Sticker: 'sticker',
    Location: 'location',
    Contact: 'contact'
} as const;

export type GroupEventLogItemMediaTypeEnum = typeof GroupEventLogItemMediaTypeEnum[keyof typeof GroupEventLogItemMediaTypeEnum];


