/* tslint:disable */
/* eslint-disable */
/**
 * Shula API
 * API documentation for the Shula application
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MediaCounts
 */
export interface MediaCounts {
    /**
     * 
     * @type {string}
     * @memberof MediaCounts
     */
    'image': MediaCountsImageEnum;
    /**
     * 
     * @type {string}
     * @memberof MediaCounts
     */
    'video': MediaCountsVideoEnum;
    /**
     * 
     * @type {string}
     * @memberof MediaCounts
     */
    'document': MediaCountsDocumentEnum;
    /**
     * 
     * @type {string}
     * @memberof MediaCounts
     */
    'audio': MediaCountsAudioEnum;
    /**
     * 
     * @type {string}
     * @memberof MediaCounts
     */
    'sticker': MediaCountsStickerEnum;
    /**
     * 
     * @type {string}
     * @memberof MediaCounts
     */
    'location': MediaCountsLocationEnum;
    /**
     * 
     * @type {string}
     * @memberof MediaCounts
     */
    'contact': MediaCountsContactEnum;
    /**
     * 
     * @type {number}
     * @memberof MediaCounts
     */
    'total': number;
}

export const MediaCountsImageEnum = {
    Image: 'image',
    Video: 'video',
    Audio: 'audio',
    Document: 'document',
    Sticker: 'sticker',
    Location: 'location',
    Contact: 'contact'
} as const;

export type MediaCountsImageEnum = typeof MediaCountsImageEnum[keyof typeof MediaCountsImageEnum];
export const MediaCountsVideoEnum = {
    Image: 'image',
    Video: 'video',
    Audio: 'audio',
    Document: 'document',
    Sticker: 'sticker',
    Location: 'location',
    Contact: 'contact'
} as const;

export type MediaCountsVideoEnum = typeof MediaCountsVideoEnum[keyof typeof MediaCountsVideoEnum];
export const MediaCountsDocumentEnum = {
    Image: 'image',
    Video: 'video',
    Audio: 'audio',
    Document: 'document',
    Sticker: 'sticker',
    Location: 'location',
    Contact: 'contact'
} as const;

export type MediaCountsDocumentEnum = typeof MediaCountsDocumentEnum[keyof typeof MediaCountsDocumentEnum];
export const MediaCountsAudioEnum = {
    Image: 'image',
    Video: 'video',
    Audio: 'audio',
    Document: 'document',
    Sticker: 'sticker',
    Location: 'location',
    Contact: 'contact'
} as const;

export type MediaCountsAudioEnum = typeof MediaCountsAudioEnum[keyof typeof MediaCountsAudioEnum];
export const MediaCountsStickerEnum = {
    Image: 'image',
    Video: 'video',
    Audio: 'audio',
    Document: 'document',
    Sticker: 'sticker',
    Location: 'location',
    Contact: 'contact'
} as const;

export type MediaCountsStickerEnum = typeof MediaCountsStickerEnum[keyof typeof MediaCountsStickerEnum];
export const MediaCountsLocationEnum = {
    Image: 'image',
    Video: 'video',
    Audio: 'audio',
    Document: 'document',
    Sticker: 'sticker',
    Location: 'location',
    Contact: 'contact'
} as const;

export type MediaCountsLocationEnum = typeof MediaCountsLocationEnum[keyof typeof MediaCountsLocationEnum];
export const MediaCountsContactEnum = {
    Image: 'image',
    Video: 'video',
    Audio: 'audio',
    Document: 'document',
    Sticker: 'sticker',
    Location: 'location',
    Contact: 'contact'
} as const;

export type MediaCountsContactEnum = typeof MediaCountsContactEnum[keyof typeof MediaCountsContactEnum];


