/* tslint:disable */
/* eslint-disable */
/**
 * Shula API
 * API documentation for the Shula application
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MessageResponseDto
 */
export interface MessageResponseDto {
    /**
     * Unique identifier of the message
     * @type {string}
     * @memberof MessageResponseDto
     */
    'id': string;
    /**
     * ID of the conversation this message belongs to
     * @type {string}
     * @memberof MessageResponseDto
     */
    'conversationId': string;
    /**
     * Type of message or event
     * @type {string}
     * @memberof MessageResponseDto
     */
    'type': MessageResponseDtoTypeEnum;
    /**
     * Text content of the message (if applicable)
     * @type {string}
     * @memberof MessageResponseDto
     */
    'content'?: string;
    /**
     * When the message was sent
     * @type {string}
     * @memberof MessageResponseDto
     */
    'timestamp': string;
    /**
     * Current status of the message
     * @type {string}
     * @memberof MessageResponseDto
     */
    'status': MessageResponseDtoStatusEnum;
    /**
     * ID of the related person (for PERSON_CREATED or PERSON_CONNECTED)
     * @type {string}
     * @memberof MessageResponseDto
     */
    'personId'?: string;
    /**
     * Photo ID attached to the message (for IMAGE_UPLOAD)
     * @type {string}
     * @memberof MessageResponseDto
     */
    'photoId'?: string;
    /**
     * Additional metadata about the message
     * @type {object}
     * @memberof MessageResponseDto
     */
    'metadata'?: object;
}

export const MessageResponseDtoTypeEnum = {
    UserMessage: 'USER_MESSAGE',
    AgentMessage: 'AGENT_MESSAGE',
    ImageUpload: 'IMAGE_UPLOAD',
    PersonCreated: 'PERSON_CREATED',
    PersonConnected: 'PERSON_CONNECTED',
    SystemEvent: 'SYSTEM_EVENT'
} as const;

export type MessageResponseDtoTypeEnum = typeof MessageResponseDtoTypeEnum[keyof typeof MessageResponseDtoTypeEnum];
export const MessageResponseDtoStatusEnum = {
    Sent: 'sent',
    Delivered: 'delivered',
    Read: 'read',
    Failed: 'failed'
} as const;

export type MessageResponseDtoStatusEnum = typeof MessageResponseDtoStatusEnum[keyof typeof MessageResponseDtoStatusEnum];


