/* tslint:disable */
/* eslint-disable */
/**
 * Shula API
 * API documentation for the Shula application
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { GroupWithCountsResponseDto } from './group-with-counts-response-dto';

/**
 * 
 * @export
 * @interface PaginatedGroupsWithCountsResponseDto
 */
export interface PaginatedGroupsWithCountsResponseDto {
    /**
     * Total number of items
     * @type {number}
     * @memberof PaginatedGroupsWithCountsResponseDto
     */
    'total': number;
    /**
     * Current page number
     * @type {number}
     * @memberof PaginatedGroupsWithCountsResponseDto
     */
    'page': number;
    /**
     * Number of items per page
     * @type {number}
     * @memberof PaginatedGroupsWithCountsResponseDto
     */
    'size': number;
    /**
     * Total number of pages
     * @type {number}
     * @memberof PaginatedGroupsWithCountsResponseDto
     */
    'pages': number;
    /**
     * Array of groups with counts
     * @type {Array<GroupWithCountsResponseDto>}
     * @memberof PaginatedGroupsWithCountsResponseDto
     */
    'items': Array<GroupWithCountsResponseDto>;
}

