/* tslint:disable */
/* eslint-disable */
/**
 * Shula API
 * API documentation for the Shula application
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PaginationMetadata
 */
export interface PaginationMetadata {
    /**
     * 
     * @type {number}
     * @memberof PaginationMetadata
     */
    'page': number;
    /**
     * 
     * @type {number}
     * @memberof PaginationMetadata
     */
    'limit': number;
    /**
     * 
     * @type {number}
     * @memberof PaginationMetadata
     */
    'total': number;
    /**
     * 
     * @type {number}
     * @memberof PaginationMetadata
     */
    'totalPages': number;
}

