/* tslint:disable */
/* eslint-disable */
/**
 * Shula API
 * API documentation for the Shula application
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PaginatedResponseDto
 */
export interface PaginatedResponseDto {
    /**
     * Array of items
     * @type {Array<string>}
     * @memberof PaginatedResponseDto
     */
    'items': Array<string>;
    /**
     * Total number of items
     * @type {number}
     * @memberof PaginatedResponseDto
     */
    'total': number;
    /**
     * Current page number
     * @type {number}
     * @memberof PaginatedResponseDto
     */
    'page': number;
    /**
     * Number of items per page
     * @type {number}
     * @memberof PaginatedResponseDto
     */
    'size': number;
    /**
     * Total number of pages
     * @type {number}
     * @memberof PaginatedResponseDto
     */
    'pages': number;
}

