/* tslint:disable */
/* eslint-disable */
/**
 * Shula API
 * API documentation for the Shula application
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { EnhancedGroupResponseDto } from './enhanced-group-response-dto';

/**
 * 
 * @export
 * @interface ParticipantContextResponseDto
 */
export interface ParticipantContextResponseDto {
    /**
     * The participant name
     * @type {string}
     * @memberof ParticipantContextResponseDto
     */
    'name': string;
    /**
     * Groups the participant belongs to
     * @type {Array<EnhancedGroupResponseDto>}
     * @memberof ParticipantContextResponseDto
     */
    'groups': Array<EnhancedGroupResponseDto>;
}

