/* tslint:disable */
/* eslint-disable */
/**
 * Shula API
 * API documentation for the Shula application
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ParticipantsUpdateStatusDto
 */
export interface ParticipantsUpdateStatusDto {
    /**
     * Participant status
     * @type {string}
     * @memberof ParticipantsUpdateStatusDto
     */
    'status': ParticipantsUpdateStatusDtoStatusEnum;
}

export const ParticipantsUpdateStatusDtoStatusEnum = {
    Active: 'active',
    Inactive: 'inactive',
    Deleted: 'deleted'
} as const;

export type ParticipantsUpdateStatusDtoStatusEnum = typeof ParticipantsUpdateStatusDtoStatusEnum[keyof typeof ParticipantsUpdateStatusDtoStatusEnum];


