/* tslint:disable */
/* eslint-disable */
/**
 * Shula API
 * API documentation for the Shula application
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ParticipantsCreateDto
 */
export interface ParticipantsCreateDto {
    /**
     * Participant phone number in international format
     * @type {string}
     * @memberof ParticipantsCreateDto
     */
    'phoneNumber': string;
    /**
     * Participant name
     * @type {string}
     * @memberof ParticipantsCreateDto
     */
    'name': string;
}

