/* tslint:disable */
/* eslint-disable */
/**
 * Shula API
 * API documentation for the Shula application
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PersonsCreateDto
 */
export interface PersonsCreateDto {
    /**
     * The name of the person
     * @type {string}
     * @memberof PersonsCreateDto
     */
    'name': string;
    /**
     * The participant ID of the creator
     * @type {string}
     * @memberof PersonsCreateDto
     */
    'participantId': string;
    /**
     * The group ID for context
     * @type {string}
     * @memberof PersonsCreateDto
     */
    'groupId': string;
    /**
     * The status of the person
     * @type {string}
     * @memberof PersonsCreateDto
     */
    'status'?: PersonsCreateDtoStatusEnum;
}

export const PersonsCreateDtoStatusEnum = {
    Active: 'active',
    Inactive: 'inactive',
    Deleted: 'deleted'
} as const;

export type PersonsCreateDtoStatusEnum = typeof PersonsCreateDtoStatusEnum[keyof typeof PersonsCreateDtoStatusEnum];


