/* tslint:disable */
/* eslint-disable */
/**
 * Shula API
 * API documentation for the Shula application
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { ParticipantInfo } from './participant-info';

/**
 * 
 * @export
 * @interface PersonsResponseDto
 */
export interface PersonsResponseDto {
    /**
     * The unique identifier of the person
     * @type {string}
     * @memberof PersonsResponseDto
     */
    'id': string;
    /**
     * The name of the person
     * @type {string}
     * @memberof PersonsResponseDto
     */
    'name': string;
    /**
     * The status of the person
     * @type {string}
     * @memberof PersonsResponseDto
     */
    'status': PersonsResponseDtoStatusEnum;
    /**
     * The date the person was created
     * @type {string}
     * @memberof PersonsResponseDto
     */
    'createdAt': string;
    /**
     * Array of AWS Rekognition face IDs associated with this person
     * @type {Array<string>}
     * @memberof PersonsResponseDto
     */
    'faceIds'?: Array<string>;
    /**
     * The AWS Rekognition collection ID where the face data is stored
     * @type {string}
     * @memberof PersonsResponseDto
     */
    'rekognitionCollectionId'?: string;
    /**
     * The group ID associated with this person
     * @type {string}
     * @memberof PersonsResponseDto
     */
    'groupId': string;
    /**
     * The participant who owns this person
     * @type {ParticipantInfo}
     * @memberof PersonsResponseDto
     */
    'participant': ParticipantInfo;
    /**
     * The relationship between the participant and the person
     * @type {string}
     * @memberof PersonsResponseDto
     */
    'relationship'?: string;
}

export const PersonsResponseDtoStatusEnum = {
    Active: 'active',
    Inactive: 'inactive',
    Deleted: 'deleted'
} as const;

export type PersonsResponseDtoStatusEnum = typeof PersonsResponseDtoStatusEnum[keyof typeof PersonsResponseDtoStatusEnum];


