/* tslint:disable */
/* eslint-disable */
/**
 * Shula API
 * API documentation for the Shula application
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RenderSystemMessageDto
 */
export interface RenderSystemMessageDto {
    /**
     * Key of the system message to render
     * @type {string}
     * @memberof RenderSystemMessageDto
     */
    'key': string;
    /**
     * Parameters to replace placeholders in the message
     * @type {object}
     * @memberof RenderSystemMessageDto
     */
    'params'?: object;
}

