/* tslint:disable */
/* eslint-disable */
/**
 * Shula API
 * API documentation for the Shula application
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WhatsAppStatusResponseDto
 */
export interface WhatsAppStatusResponseDto {
    /**
     * Whether the WhatsApp connection is healthy
     * @type {boolean}
     * @memberof WhatsAppStatusResponseDto
     */
    'isHealthy': boolean;
    /**
     * Current state of the WhatsApp connection
     * @type {string}
     * @memberof WhatsAppStatusResponseDto
     */
    'state': string | null;
    /**
     * Number of consecutive connection failures
     * @type {number}
     * @memberof WhatsAppStatusResponseDto
     */
    'failureCount': number;
    /**
     * Whether a QR code is available
     * @type {boolean}
     * @memberof WhatsAppStatusResponseDto
     */
    'hasQrCode': boolean;
    /**
     * Timestamp of the last status update
     * @type {string}
     * @memberof WhatsAppStatusResponseDto
     */
    'updatedAt': string;
}

