/* tslint:disable */
/* eslint-disable */
/**
 * Shula API
 * API documentation for the Shula application
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface WhatsAppQrCodeResponseDto
 */
export interface WhatsAppQrCodeResponseDto {
    /**
     * QR code string for WhatsApp authentication
     * @type {string}
     * @memberof WhatsAppQrCodeResponseDto
     */
    'qrCode': string | null;
    /**
     * Timestamp when the QR code was generated
     * @type {string}
     * @memberof WhatsAppQrCodeResponseDto
     */
    'updatedAt': string | null;
}

